#ifndef _TEMPERATURE_INPUTS_DEFINES_ASM_INCLUDED_
#define _TEMPERATURE_INPUTS_DEFINES_ASM_INCLUDED_


#define TEMPERATURE_INPUTS_OFFSET_HW_BIT_INFO		0x00		// length: 1 byte
#define TEMPERATURE_INPUTS_OFFSET_COMMAND_STATE		0x01		// length: 1 byte
#define TEMPERATURE_INPUTS_OFFSET_BYTES_TO_WRITE	0x02		// length: 1 byte
#define TEMPERATURE_INPUTS_OFFSET_READ_BYTES		0x03		// length: 1 byte
#define TEMPERATURE_INPUTS_OFFSET_UNUSED_01			0x04		// length: 12 bytes
#define TEMPERATURE_INPUTS_OFFSET_WRITE_BUFFER		0x10		// length: 32 bytes
#define TEMPERATURE_INPUTS_OFFSET_READ_BUFFER		0x30		// length: 32 bytes

#define HW_BIT_INFO 0x00
#define COMMAND_STATE 0x01
#define WRITE_BYTE_CNT PT_TEMP_IN_DATA+0x02
#define READ_BYTE_CNT PT_TEMP_IN_DATA+0x03


#endif //  _TEMPERATURE_INPUTS_DEFINES_ASM_INCLUDED_
